[package]
name = "detamu-engine"
description = "Standalone Detamu engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "detamu"
path = "src/main.rs"

[dependencies]
detamu-sdk = { path = "../detamu-sdk" }
detamu-store.workspace = true
serde_json.workspace = true

[lints]
workspace = true

