[package]
name = "detamu-engine"
description = "Standalone Detamu engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "detamu"
path = "src/main.rs"

[dependencies]
detamu-code-coverage.workspace = true
detamu-model.workspace = true
detamu-model-code.workspace = true
detamu-language-lizard.workspace = true
detamu-language-rust.workspace = true
detamu-language-rust-analyzer.workspace = true
detamu-language.workspace = true
detamu-sdk = { path = "../detamu-sdk" }
detamu-source-git.workspace = true
detamu-store.workspace = true
detamu-surreal = { path = "../detamu-surreal" }
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
